### PR TITLE
Handle disabled nodes

### PR DESCRIPTION
**Pull request by mripard**
Hi,

This fixes the issue we've discussed on the ML and in the issue tracker for spurious missing properties messages for the disabled nodes.

### CODE REVIEW

**Review by robherring — COMMENTED** [review]
My main concern here is this doubles the number of schema. For each node, we check 'select' on every schema. It's not a problem now, but I worry about when we have 3000 of them which is roughly how many bindings docs we have.

We can do the error filtering with just this change:

```
diff --git a/dtschema/lib.py b/dtschema/lib.py
index 802fe59e1a8d..11ae99a7ab7c 100644
--- a/dtschema/lib.py
+++ b/dtschema/lib.py
@@ -505,6 +505,9 @@ class DTValidator(DTVal):
 
     def iter_errors(self, instance, _schema=None):
         for error in jsonschema.Draft6Validator.iter_errors(self, instance, _schema):
+            if isinstance(instance, dict) and 'status' in instance.keys() and \
+                instance['status'] == ['disabled'] and 'required property' in error.message:
+                continue
             error.linecol = get_line_col(instance, error.path)
             yield error
 
```

**Comment by mripard** [comment]
Yeah, that would work as well. Do you want to commit the patch yourself?

**Comment by mripard** [comment]
It looks like there's a bit more to it though.

The continue statement seems to confuse some other part of the tools and it ends up dumping the entire schema. Removing the continue (with a print for example) behaves properly though.

**Comment by robherring** [comment]
I don't follow. Without 'continue' the behavior would not be changed.

**Comment by mripard** [comment]
With current master, a dt-validate run looks like this:
```
$ ~/Work/src/yaml-bindings/tools/dt-validate -p ./Documentation/devicetree/bindings/processed-schema.yaml arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml 
/home/max/Work/allwinner/build/kernel/arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml: 'ranges' does not match any of the regexes: '^framebuffer'
```

With the patch
```
diff --git a/dtschema/lib.py b/dtschema/lib.py
index f72626b7070c..276bdd7b237a 100644
--- a/dtschema/lib.py
+++ b/dtschema/lib.py
@@ -521,6 +521,11 @@ class DTValidator(DTVal):
 
     def iter_errors(self, instance, _schema=None):
         for error in jsonschema.Draft6Validator.iter_errors(self, instance, _schema):
+            if isinstance(instance, dict) and 'status' in instance and \
+               'disabled' in instance['status'] and \
+               'required property' in error.message:
+                print("
+
             error.linecol = get_line_col(instance, error.path)
             yield error
```
That same command output is:
```$ ~/Work/src/yaml-bindings/tools/dt-validate -p ./Documentation/devicetree/bindings/processed-schema.yaml arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml 
/home/max/Work/allwinner/build/kernel/arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml: 'ranges' does not match any of the regexes: '^framebuffer'
node is disabled
node is disabled
node is disabled
node is disabled
```
And if we replace the print by a continue
```
$ ~/Work/src/yaml-bindings/tools/dt-validate -p ./Documentation/devicetree/bindings/processed-schema.yaml arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml 
/home/max/Work/allwinner/build/kernel/arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml: 'ranges' does not match any of the regexes: '^framebuffer'
/home/max/Work/allwinner/build/kernel/arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml: {'#sound-dai-cells': [[0]], 'compatible': ['allwinner,sun8i-h3-spdif'], 'reg': [[29495296, 1024]], 'interrupts': [[0, 12, 4]], 'clocks': [[3, 53], [3, 87]], 'resets': [[3, 41]], 'clock-names': ['apb', 'spdif'], 'dmas': [[19, 2]], 'dma-names': ['tx', 'rx'], 'status': ['disabled'], '$nodename': ['spdif@1c21000']} is valid under each of {'required': ['interrupts-extended']}, {'required': ['interrupts']}
{'$filename': '/home/max/Work/src/linux/Documentation/devicetree/bindings/sound/allwinner,sun4i-a10-spdif.yaml',
 '$id': 'http://devicetree.org/schemas/sound/allwinner,sun4i-a10-spdif.yaml#',
 '$schema': 'http://devicetree.org/meta-schemas/core.yaml#',
 '$select_validator': <jsonschema.validators.create.<locals>.Validator object at 0x7fd5a5d9fef0>,
 'additionalProperties': False,
 'allOf': [{'if': {'properties': {'compatible': {'contains': {'enum': ['allwinner,sun6i-a31-spdif',
                                                                       'allwinner,sun8i-h3-spdif']}}}},
            'then': {'required': ['resets']}},
           {'else': {'properties': {'dma-names': {'items': [{'const': 'rx'},
                                                            {'const': 'tx'}],
                                                  'maxItems': 2,
                                                  'minItems': 2},
                                    'dmas': {'items': [{}, {}],
                                             'maxItems': 2,
                                             'minItems': 2}}},
            'if': {'properties': {'compatible': {'items': [{'const': 'allwinner,sun8i-h3-spdif'}]}}},
            'then': {'properties': {'dma-names': {'const': 'tx'},
                                    'dmas': {'maxItems': 2}}}}],
 'oneOf': [{'required': ['interrupts']},
           {'required': ['interrupts-extended']}],
 'properties': {'#sound-dai-cells': {'additionalItems': False,
                                     'items': {'additionalItems': False,
                                               'items': {'const': 0},
                                               'maxItems': 1,
                                               'minItems': 1,
                                               'type': 'array'},
                                     'maxItems': 1,
                                     'minItems': 1,
                                     'type': 'array'},
                '$nodename': True,
                'clock-names': {'additionalItems': False,
                                'items': [{'const': 'apb'},
                                          {'const': 'spdif'}],
                                'maxItems': 2,
                                'minItems': 2,
                                'type': 'array'},
                'clocks': {'additionalItems': False,
                           'items': [{}, {}],
                           'maxItems': 2,
                           'minItems': 2,
                           'type': 'array'},
                'compatible': {'oneOf': [{'additionalItems': False,
                                          'items': {'const': 'allwinner,sun4i-a10-spdif'},
                                          'maxItems': 1,
                                          'minItems': 1,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': {'const': 'allwinner,sun6i-a31-spdif'},
                                          'maxItems': 1,
                                          'minItems': 1,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': {'const': 'allwinner,sun8i-h3-spdif'},
                                          'maxItems': 1,
                                          'minItems': 1,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'const': 'allwinner,sun8i-a83t-spdif'},
                                                    {'const': 'allwinner,sun8i-h3-spdif'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'const': 'allwinner,sun50i-a64-spdif'},
                                                    {'const': 'allwinner,sun8i-h3-spdif'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'}]},
                'dma-names': True,
                'dmas': True,
                'interrupt-parent': True,
                'interrupts': {'maxItems': 1, 'minItems': 1},
                'interrupts-extended': {'$ref': '#/properties/interrupts'},
                'phandle': True,
                'reg': {'maxItems': 1, 'minItems': 1},
                'resets': {'maxItems': 1, 'minItems': 1},
                'status': True},
 'required': ['#sound-dai-cells',
              'compatible',
              'reg',
              'clocks',
              'clock-names',
              'dmas',
              'dma-names'],
 'select': {'properties': {'compatible': {'contains': {'enum': ['allwinner,sun50i-a64-spdif',
                                                                'allwinner,sun6i-a31-spdif',
                                                                'allwinner,sun8i-h3-spdif',
                                                                'allwinner,sun4i-a10-spdif',
                                                                'allwinner,sun8i-a83t-spdif']}}},
            'required': ['compatible']},
 'title': 'Allwinner A10 S/PDIF Controller Device Tree Bindings'}
/home/max/Work/allwinner/build/kernel/arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml: {'compatible': ['snps,dw-apb-uart'], 'reg': [[29524992, 1024]], 'interrupts': [[0, 1, 4]], 'reg-shift': [[2]], 'reg-io-width': [[4]], 'clocks': [[3, 63]], 'resets': [[3, 50]], 'dmas': [[19, 7], [19, 7]], 'dma-names': ['rx', 'tx'], 'status': ['disabled'], '$nodename': ['serial@1c28400']} is valid under each of {'required': ['interrupts-extended']}, {'required': ['interrupts']}
{'$filename': '/home/max/Work/src/linux/Documentation/devicetree/bindings/serial/snps-dw-apb-uart.yaml',
 '$id': 'http://devicetree.org/schemas/serial/snps-dw-apb-uart.yaml#',
 '$schema': 'http://devicetree.org/meta-schemas/core.yaml#',
 '$select_validator': <jsonschema.validators.create.<locals>.Validator object at 0x7fd5a5d9fb00>,
 'allOf': [{'$ref': '/schemas/serial.yaml#'}],
 'oneOf': [{'required': ['interrupts']},
           {'required': ['interrupts-extended']}],
 'properties': {'$nodename': True,
                'clock-frequency': True,
                'clock-names': {'additionalItems': False,
                                'items': [{'const': 'baudclk'},
                                          {'const': 'apb_pclk'}],
                                'maxItems': 2,
                                'minItems': 2,
                                'type': 'array'},
                'clocks': {'maxItems': 2, 'minItems': 1},
                'compatible': {'oneOf': [{'additionalItems': False,
                                          'items': [{'enum': ['renesas,r9a06g032-uart',
                                                              'renesas,r9a06g033-uart']},
                                                    {'const': 'renesas,rzn1-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'enum': ['rockchip,px30-uart',
                                                              'rockchip,rk3036-uart',
                                                              'rockchip,rk3066-uart',
                                                              'rockchip,rk3188-uart',
                                                              'rockchip,rk3288-uart',
                                                              'rockchip,rk3328-uart',
                                                              'rockchip,rk3368-uart',
                                                              'rockchip,rk3399-uart',
                                                              'rockchip,rv1108-uart']},
                                                    {'const': 'snps,dw-apb-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'enum': ['brcm,bcm11351-dw-apb-uart',
                                                              'brcm,bcm21664-dw-apb-uart']},
                                                    {'const': 'snps,dw-apb-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': {'const': 'snps,dw-apb-uart'},
                                          'maxItems': 1,
                                          'minItems': 1,
                                          'type': 'array'}]},
                'cts-override': {'type': 'boolean'},
                'dcd-override': {'type': 'boolean'},
                'dsr-override': {'type': 'boolean'},
                'interrupt-parent': True,
                'interrupts': {'maxItems': 1, 'minItems': 1},
                'interrupts-extended': {'$ref': '#/properties/interrupts'},
                'phandle': True,
                'reg': {'maxItems': 1, 'minItems': 1},
                'reg-io-width': True,
                'reg-shift': True,
                'resets': {'maxItems': 1, 'minItems': 1},
                'ri-override': {'type': 'boolean'},
                'snps,uart-16550-compatible': {'type': 'boolean'},
                'status': True},
 'required': ['compatible', 'reg'],
 'select': {'properties': {'compatible': {'contains': {'enum': ['renesas,r9a06g032-uart',
                                                                'rockchip,rv1108-uart',
                                                                'rockchip,rk3288-uart',
                                                                'rockchip,rk3328-uart',
                                                                'renesas,rzn1-uart',
                                                                'rockchip,px30-uart',
                                                                'rockchip,rk3399-uart',
                                                                'snps,dw-apb-uart',
                                                                'rockchip,rk3066-uart',
                                                                'rockchip,rk3368-uart',
                                                                'renesas,r9a06g033-uart',
                                                                'rockchip,rk3036-uart',
                                                                'brcm,bcm21664-dw-apb-uart',
                                                                'rockchip,rk3188-uart',
                                                                'brcm,bcm11351-dw-apb-uart']}}},
            'required': ['compatible']},
 'title': 'Synopsys DesignWare ABP UART'}
/home/max/Work/allwinner/build/kernel/arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml: {'compatible': ['snps,dw-apb-uart'], 'reg': [[29526016, 1024]], 'interrupts': [[0, 2, 4]], 'reg-shift': [[2]], 'reg-io-width': [[4]], 'clocks': [[3, 64]], 'resets': [[3, 51]], 'dmas': [[19, 8], [19, 8]], 'dma-names': ['rx', 'tx'], 'status': ['disabled'], '$nodename': ['serial@1c28800']} is valid under each of {'required': ['interrupts-extended']}, {'required': ['interrupts']}
{'$filename': '/home/max/Work/src/linux/Documentation/devicetree/bindings/serial/snps-dw-apb-uart.yaml',
 '$id': 'http://devicetree.org/schemas/serial/snps-dw-apb-uart.yaml#',
 '$schema': 'http://devicetree.org/meta-schemas/core.yaml#',
 '$select_validator': <jsonschema.validators.create.<locals>.Validator object at 0x7fd5a5d9fb00>,
 'allOf': [{'$ref': '/schemas/serial.yaml#'}],
 'oneOf': [{'required': ['interrupts']},
           {'required': ['interrupts-extended']}],
 'properties': {'$nodename': True,
                'clock-frequency': True,
                'clock-names': {'additionalItems': False,
                                'items': [{'const': 'baudclk'},
                                          {'const': 'apb_pclk'}],
                                'maxItems': 2,
                                'minItems': 2,
                                'type': 'array'},
                'clocks': {'maxItems': 2, 'minItems': 1},
                'compatible': {'oneOf': [{'additionalItems': False,
                                          'items': [{'enum': ['renesas,r9a06g032-uart',
                                                              'renesas,r9a06g033-uart']},
                                                    {'const': 'renesas,rzn1-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'enum': ['rockchip,px30-uart',
                                                              'rockchip,rk3036-uart',
                                                              'rockchip,rk3066-uart',
                                                              'rockchip,rk3188-uart',
                                                              'rockchip,rk3288-uart',
                                                              'rockchip,rk3328-uart',
                                                              'rockchip,rk3368-uart',
                                                              'rockchip,rk3399-uart',
                                                              'rockchip,rv1108-uart']},
                                                    {'const': 'snps,dw-apb-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'enum': ['brcm,bcm11351-dw-apb-uart',
                                                              'brcm,bcm21664-dw-apb-uart']},
                                                    {'const': 'snps,dw-apb-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': {'const': 'snps,dw-apb-uart'},
                                          'maxItems': 1,
                                          'minItems': 1,
                                          'type': 'array'}]},
                'cts-override': {'type': 'boolean'},
                'dcd-override': {'type': 'boolean'},
                'dsr-override': {'type': 'boolean'},
                'interrupt-parent': True,
                'interrupts': {'maxItems': 1, 'minItems': 1},
                'interrupts-extended': {'$ref': '#/properties/interrupts'},
                'phandle': True,
                'reg': {'maxItems': 1, 'minItems': 1},
                'reg-io-width': True,
                'reg-shift': True,
                'resets': {'maxItems': 1, 'minItems': 1},
                'ri-override': {'type': 'boolean'},
                'snps,uart-16550-compatible': {'type': 'boolean'},
                'status': True},
 'required': ['compatible', 'reg'],
 'select': {'properties': {'compatible': {'contains': {'enum': ['renesas,r9a06g032-uart',
                                                                'rockchip,rv1108-uart',
                                                                'rockchip,rk3288-uart',
                                                                'rockchip,rk3328-uart',
                                                                'renesas,rzn1-uart',
                                                                'rockchip,px30-uart',
                                                                'rockchip,rk3399-uart',
                                                                'snps,dw-apb-uart',
                                                                'rockchip,rk3066-uart',
                                                                'rockchip,rk3368-uart',
                                                                'renesas,r9a06g033-uart',
                                                                'rockchip,rk3036-uart',
                                                                'brcm,bcm21664-dw-apb-uart',
                                                                'rockchip,rk3188-uart',
                                                                'brcm,bcm11351-dw-apb-uart']}}},
            'required': ['compatible']},
 'title': 'Synopsys DesignWare ABP UART'}
/home/max/Work/allwinner/build/kernel/arch/arm/boot/dts/sun8i-h3-rervision-dvk.dt.yaml: {'compatible': ['snps,dw-apb-uart'], 'reg': [[29527040, 1024]], 'interrupts': [[0, 3, 4]], 'reg-shift': [[2]], 'reg-io-width': [[4]], 'clocks': [[3, 65]], 'resets': [[3, 52]], 'dmas': [[19, 9], [19, 9]], 'dma-names': ['rx', 'tx'], 'status': ['disabled'], '$nodename': ['serial@1c28c00']} is valid under each of {'required': ['interrupts-extended']}, {'required': ['interrupts']}
{'$filename': '/home/max/Work/src/linux/Documentation/devicetree/bindings/serial/snps-dw-apb-uart.yaml',
 '$id': 'http://devicetree.org/schemas/serial/snps-dw-apb-uart.yaml#',
 '$schema': 'http://devicetree.org/meta-schemas/core.yaml#',
 '$select_validator': <jsonschema.validators.create.<locals>.Validator object at 0x7fd5a5d9fb00>,
 'allOf': [{'$ref': '/schemas/serial.yaml#'}],
 'oneOf': [{'required': ['interrupts']},
           {'required': ['interrupts-extended']}],
 'properties': {'$nodename': True,
                'clock-frequency': True,
                'clock-names': {'additionalItems': False,
                                'items': [{'const': 'baudclk'},
                                          {'const': 'apb_pclk'}],
                                'maxItems': 2,
                                'minItems': 2,
                                'type': 'array'},
                'clocks': {'maxItems': 2, 'minItems': 1},
                'compatible': {'oneOf': [{'additionalItems': False,
                                          'items': [{'enum': ['renesas,r9a06g032-uart',
                                                              'renesas,r9a06g033-uart']},
                                                    {'const': 'renesas,rzn1-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'enum': ['rockchip,px30-uart',
                                                              'rockchip,rk3036-uart',
                                                              'rockchip,rk3066-uart',
                                                              'rockchip,rk3188-uart',
                                                              'rockchip,rk3288-uart',
                                                              'rockchip,rk3328-uart',
                                                              'rockchip,rk3368-uart',
                                                              'rockchip,rk3399-uart',
                                                              'rockchip,rv1108-uart']},
                                                    {'const': 'snps,dw-apb-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': [{'enum': ['brcm,bcm11351-dw-apb-uart',
                                                              'brcm,bcm21664-dw-apb-uart']},
                                                    {'const': 'snps,dw-apb-uart'}],
                                          'maxItems': 2,
                                          'minItems': 2,
                                          'type': 'array'},
                                         {'additionalItems': False,
                                          'items': {'const': 'snps,dw-apb-uart'},
                                          'maxItems': 1,
                                          'minItems': 1,
                                          'type': 'array'}]},
                'cts-override': {'type': 'boolean'},
                'dcd-override': {'type': 'boolean'},
                'dsr-override': {'type': 'boolean'},
                'interrupt-parent': True,
                'interrupts': {'maxItems': 1, 'minItems': 1},
                'interrupts-extended': {'$ref': '#/properties/interrupts'},
                'phandle': True,
                'reg': {'maxItems': 1, 'minItems': 1},
                'reg-io-width': True,
                'reg-shift': True,
                'resets': {'maxItems': 1, 'minItems': 1},
                'ri-override': {'type': 'boolean'},
                'snps,uart-16550-compatible': {'type': 'boolean'},
                'status': True},
 'required': ['compatible', 'reg'],
 'select': {'properties': {'compatible': {'contains': {'enum': ['renesas,r9a06g032-uart',
                                                                'rockchip,rv1108-uart',
                                                                'rockchip,rk3288-uart',
                                                                'rockchip,rk3328-uart',
                                                                'renesas,rzn1-uart',
                                                                'rockchip,px30-uart',
                                                                'rockchip,rk3399-uart',
                                                                'snps,dw-apb-uart',
                                                                'rockchip,rk3066-uart',
                                                                'rockchip,rk3368-uart',
                                                                'renesas,r9a06g033-uart',
                                                                'rockchip,rk3036-uart',
                                                                'brcm,bcm21664-dw-apb-uart',
                                                                'rockchip,rk3188-uart',
                                                                'brcm,bcm11351-dw-apb-uart']}}},
            'required': ['compatible']},
 'title': 'Synopsys DesignWare ABP UART'}
```
All of these have a status = "disabled", so I'm guessing the continue has a side effect.

**Comment by robherring** [comment]
I figured out what's happening here. The problem is the required entries under a oneOf which is how we handle interrupts vs. interrupts-extended. If we filter out the required failures, then all the oneOf clauses are true and the oneOf fails. We can fix this by using anyOf instead, but that's not really correct.

We'd have to generate all the warnings and then filter them instead of doing it in iter_errors for this to work.

**Comment by mripard** [comment]
I just submitted something along those lines on the devicetree-org repo. I'll close this one. Thanks!

**Pull request closed without merging**
